name: dm4dh
dependencies:
  - python
  - pip
  - nmslib==2.1.1
  - numpy>=1.23.2
  - pip: 
      - pandas<2.0.0
      - scikit-learn==1.3.1
      - seaborn==0.12.2
      - ipywidgets==8.1.1
      - scispacy==0.5.1
      - gensim==4.3.2
      - openai==1.3.5
      - tiktoken==0.5.1